# Generated by Django 6.1.1 on 2026-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenessarticle',
            name='content_hi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='awarenessarticle',
            name='title_hi',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
